spring.application.name=springEntity
spring.datasource.url=jdbc:mysql://localhost:3306/spring_entity?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=110603
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# B?t cache trong Spring
#spring.cache.type=ehcache
#spring.cache.ehcache.config=classpath:ehcache.xml